// Generated by contracts/script/Deploy.s.sol. Do not edit by hand.
window.AFTERHOURS_CONFIG = {
  network: { name: "Robinhood Chain Testnet", chainId: 46630, rpcUrl: "https://rpc.testnet.chain.robinhood.com", explorer: "https://explorer.testnet.chain.robinhood.com" },
  deployBlock: 128715968,
  contracts: {
    usdg: "0xf5780Ea23BFfFf2cD786c154Abce7147793dA2a9",
    oracle: "0x97f1aA9486FD9a516b302F88C6935762c8a143Ea",
    pool: "0xD39c71867e9d6b99169E21bdA4A231AA995C251d",
    demo: "0x548bd45c901bCF520c11831B06d8E818b16E81F7"
  },
  assets: ["0xD699b530738afa2aAfC2c573Be403937497DD18C", "0xC1525d19F9c4888E15C5A462E5a7DAbaC9d1F55D", "0xDA33FB66934D615EB500cE8E7e693DBBF1727d45", "0x5769ae06B1ae192F8c3DE5398Bca8Fbf7522bbc1"]
};
