// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console2} from "forge-std/Script.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";

import {MockUSDG} from "../src/MockUSDG.sol";
import {StockToken} from "../src/StockToken.sol";
import {MarketOracle} from "../src/MarketOracle.sol";
import {AfterHoursPool} from "../src/AfterHoursPool.sol";
import {DemoController} from "../src/DemoController.sol";

/// @notice Deploys the full AfterHours stack, seeds liquidity, and writes ../frontend/config.js.
/// Env: PRIVATE_KEY (required), NETWORK_NAME, PUBLIC_RPC_URL, EXPLORER_URL, GRACE_SECONDS
contract Deploy is Script {
    struct Listing {
        string name;
        string symbol;
        uint256 price; // 8 decimals
        uint256 faucet; // tokens, 18 decimals
        uint16 ltvOpen;
        uint16 ltvClosed;
        uint16 liqThreshold;
        uint16 liqBonus;
    }

    MockUSDG usdg;
    MarketOracle oracle;
    AfterHoursPool pool;
    DemoController demo;
    address[] tokens;

    function run() external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(pk);
        uint64 grace = uint64(vm.envOr("GRACE_SECONDS", uint256(15)));

        Listing[] memory listings = new Listing[](4);
        listings[0] = Listing("NVIDIA Corp (Tokenized)", "tNVDA", 185e8, 40e18, 6000, 4000, 7000, 600);
        listings[1] = Listing("Apple Inc (Tokenized)", "tAAPL", 230e8, 30e18, 6500, 4500, 7500, 500);
        listings[2] = Listing("Tesla Inc (Tokenized)", "tTSLA", 260e8, 25e18, 5000, 3000, 6200, 800);
        listings[3] = Listing("S&P 500 ETF (Tokenized)", "tSPY", 570e8, 15e18, 7000, 5500, 7800, 400);

        vm.startBroadcast(pk);

        usdg = new MockUSDG(deployer);
        oracle = new MarketOracle(deployer, 1 hours, grace);
        pool = new AfterHoursPool(IERC20(address(usdg)), oracle, deployer);
        demo = new DemoController(usdg, oracle, pool, deployer);

        usdg.setMinter(address(demo), true);
        usdg.setMinter(deployer, true);
        oracle.setKeeper(address(demo), true);
        oracle.setMarketOpen(true);

        for (uint256 i; i < listings.length; ++i) {
            Listing memory l = listings[i];
            StockToken t = new StockToken(l.name, l.symbol, deployer);
            t.setMinter(address(demo), true);
            t.transferOwnership(address(demo));
            oracle.setPrice(address(t), l.price);
            pool.listAsset(
                address(t),
                AfterHoursPool.AssetConfig({
                    listed: true,
                    borrowEnabled: true,
                    ltvOpenBps: l.ltvOpen,
                    ltvClosedBps: l.ltvClosed,
                    liqThresholdBps: l.liqThreshold,
                    liqBonusBps: l.liqBonus
                })
            );
            demo.addAsset(address(t), l.price, l.faucet);
            tokens.push(address(t));
        }

        // Seed lender liquidity and the gap reserve so the demo works from the first click.
        usdg.mint(deployer, 2_500_000e6);
        usdg.approve(address(pool), type(uint256).max);
        pool.supply(2_000_000e6);
        pool.fundGapReserve(50_000e6);

        vm.stopBroadcast();

        _writeConfig();

        console2.log("USDG          ", address(usdg));
        console2.log("MarketOracle  ", address(oracle));
        console2.log("AfterHoursPool", address(pool));
        console2.log("DemoController", address(demo));
    }

    function _writeConfig() internal {
        string memory network = vm.envOr("NETWORK_NAME", string("Local Anvil"));
        string memory rpc = vm.envOr("PUBLIC_RPC_URL", string("http://127.0.0.1:8545"));
        string memory explorer = vm.envOr("EXPLORER_URL", string(""));

        string memory assetsJs = "";
        for (uint256 i; i < tokens.length; ++i) {
            assetsJs = string.concat(assetsJs, i == 0 ? "" : ", ", '"', vm.toString(tokens[i]), '"');
        }

        string memory js = string.concat(
            "// Generated by contracts/script/Deploy.s.sol. Do not edit by hand.\n",
            "window.AFTERHOURS_CONFIG = {\n",
            '  network: { name: "', network, '", chainId: ', vm.toString(block.chainid),
            ', rpcUrl: "', rpc, '", explorer: "', explorer, '" },\n',
            "  deployBlock: ", vm.toString(block.number), ",\n"
        );
        js = string.concat(
            js,
            '  contracts: {\n    usdg: "', vm.toString(address(usdg)),
            '",\n    oracle: "', vm.toString(address(oracle)),
            '",\n    pool: "', vm.toString(address(pool)),
            '",\n    demo: "', vm.toString(address(demo)), '"\n  },\n',
            "  assets: [", assetsJs, "]\n};\n"
        );
        vm.writeFile("../frontend/config.js", js);
    }
}
